name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Configure pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: python -m pip install --upgrade pip && python -m pip install -r cache/requirements.txt
      
      - name: Generate Repository Archive
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python generate_repo_archive.py
      
      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
          BIRTHDAY: ${{ secrets.BIRTHDAY }}
        run: python today.py
      
      - name: Commit and Push Changes
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |-
          git config --global user.email "darshchaurasia@gmail.com"
          git config --global user.name "darshchaurasia"
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/darshchaurasia/darshchaurasia.git
          git add .
          git commit -m "📝 Updated README and Repository Archive" || echo "No changes to commit"
          git push origin main

